version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_HOST: "mongo"
      HOST_IP: "0.0.0.0"
      PORT:    "5000"
    depends_on:
      - mongo
    ports:
      - "80:5000"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    container_name: mongo-exprass
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
    depends_on:
      - mongo
    ports:
      - "8081:8081"